### ISSUE TITLE
Not reading ansible.cfg file

### ISSUE THREAD

**Issue by moet78** [StackStorm-Exchange/stackstorm-ansible#38]
When I try to execute our ansible playbook with the module, it does not seem to be reading the ansible.cfg at all. So most of my job fails due to host key or wrong user issue. 

What do you need to set for the module to read ansible.cfg?

**Comment by arm4b** [comment]
Do you mean that without module ansible.cfg works well? Where are you currently placing your `ansible.cfg`?
What's output you're seeing for the `/opt/stackstorm/virtualenvs/ansible/bin/ansible --version` command?

**Comment by moet78** [comment]
If I run it in script like "cd /opt/ansible; ansible-playbook something something", and the ansible.cfg is in /opt/ansible then yes the ansible.cfg works.

The version output is:
```
root@c3acd3d56a56:/opt# /opt/stackstorm/virtualenvs/ansible/bin/ansible --version
/opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
ansible 2.8.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/stackstorm/virtualenvs/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
```

**Comment by moet78** [comment]
and by the way when I use the module through the ansible actions in UI, I only have a place to specify which inventory file to use, but no place for ansible.cfg. 

Am I missing something obvious?

**Comment by arm4b** [comment]
Try following official Ansible docs (https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file https://docs.ansible.com/ansible/latest/installation_guide/intro_configuration.html) and using `/etc/ansible/ansible.cfg` or `ANSIBLE_CONFIG` env variable to override Ansible config file.

Once done, verify if config file is picked up via `/opt/stackstorm/virtualenvs/ansible/bin/ansible --version`

**Comment by moet78** [comment]
That did work.. thanks!
