### ISSUE TITLE
Ansible playbooks not running with stackstorm on ubuntu 18.04 with ansible pack

### ISSUE THREAD

**Issue by lenba** [StackStorm-Exchange/stackstorm-ansible#40]
OS: Ubuntu 18.04
Installation method: One liner

I have an ansible playbook that runs in ansible fine, but fails in stackstorm using ansible pack.

Error:

`
"stderr": "Traceback (most recent call last):\n  File \"/opt/stackstorm/packs/ansible/actions/ansible_playbook.py\", line 4, in <module>\n    from lib.ansible_base import AnsibleBaseRunner\n  File \"/opt/stackstorm/packs/ansible/actions/lib/ansible_base.py\", line 4, in <module>\n    import shell\nModuleNotFoundError: No module named 'shell'"
`
Accoring to https://docs.stackstorm.com/install/u18.html 

> StackStorm on Ubuntu 18.04 runs all services, actions and sensors using Python 3 only. It does not support Python2 actions.

Could this be an issue?

@nmaludy suggested this could be:

> bug in the ansible pack or maybe stackstorm core might not be setting up the PYTHONPATH correctly

Could someone have a look?

**Comment by nmaludy** [comment]
Looks like: https://github.com/StackStorm-Exchange/stackstorm-ansible/blob/master/actions/lib/ansible_base.py#L4
is trying to `import shell` and `shell.py` is in `actions/lib/` .

Guessing this is some sort of PYTHON_PATH issue in Python 3.

@Kami i know you've done some work on this and might know where to look?

Alternatively we could move the code in `lib/shell.py` into `lib/ansible_base.py` since it looks like that's the  only place where the code is used.

**Comment by gopivalleru** [comment]
I've ran ansible playbook for stackstorm on Ubuntu 18. Below are the changes I had to make

1. Mongo DB changes to support 4.0:
StackStorm.mongodb/defaults/main.yml
mongodb_version: "4.0"

mongodb_apt_keys:
  "3.2": "42F3E95A2C4F08279C4960ADD68FA50FEA312927"
  "3.4": "0C49F3730359A14518585931BC711F9BA15703C6"
  "4.0": "9da31620334bd75d9dcb49f368818c72e52529d4"

2. changed print command to python 3 compatible.
StackStorm.st2/tasks/version.yml
under task: Get installed st2 version
 change command: /opt/stackstorm/st2/bin/python -c 'import st2common; print st2common.__version__'

to

  command: /opt/stackstorm/st2/bin/python -c 'import st2common; print(st2common.__version__)'

3. Mistral is not supported on Ubuntu 18.04

comment or remove StackStorm.st2mistral role from stackstorm.yml role.

**Comment by arm4b** [comment]
Thanks for report @lenba!
Confirming it's a bug with python 3 imports in latest st2 (3.1.0).

Good point @nmaludy, might be indeed related to python 3 path/libs workarounds: https://github.com/StackStorm/st2/pull/4674 and https://github.com/StackStorm/st2/pull/4666

**Comment by arm4b** [comment]
This should be fixed, @lenba 
Needed an easy compatibility fix for this pack to work under python 3.

You can try again by re-installing the pack `st2 pack install ansible`

**Comment by lenba** [comment]
Works. Great job guys, appreciate the quick resolution. Thank you!

**Comment by Kami** [comment]
Yeah, thanks to @armab for a fix which I believe is the correct one.

Usually it's the best to avoid names which clash with standard library, but when that is not possible, relative imports (as implemented in #41 by @armab) are preferred.

**Comment by Kami** [comment]
On a related note - we should have a look why out CI didn't catch this issue.

Likely we need some more checks which also try to import the action in the same manner as StackStorm action runner would do it.
