### ISSUE TITLE
Allow relative paths to playbooks that are part of the automation pack

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm-Exchange/stackstorm-ansible#9]
I would like to store some of my playbooks with the StackStorm workflows that call them.

Right now, their is no current working directory for the action-runner, so relative paths can't be resolved by `ansible-playbook`.

So, I see two ways to add playbook-in-the-pack support:
1) Set the current working directory to the pack directory
2) Check for relative paths before passing them to `ansible-playbook` and resolve them to a directory inside the pack directory

Also, what should the paths be relative to? The pack directory itself, or the action directory? I think I would be okay with (assuming packs are installed in `/opt/stackstorm/packs/`) one of these:

* `/opt/stackstorm/packs/<pack>/`
* `/opt/stackstorm/packs/<pack>/actions/`
* `/opt/stackstorm/packs/<pack>/actions/playbooks/`
* `/opt/stackstorm/packs/<pack>/playbooks/`

If we did a path relative to a standard playbooks directory, then the existence of the directory would implictly enable/disable relative paths for actions in that automation pack.

**Comment by cognifloyd** [comment]
> * `/opt/stackstorm/packs/<pack>/actions/playbooks/`
> * `/opt/stackstorm/packs/<pack>/playbooks/`

I think I would prefer the `<pack>/playbooks` directory because the playbooks might be specified in an action workflow (as a parameter to an `ansible.playbook` action) or directly in a rule that uses the `action.playbook` action.

**Comment by arm4b** [comment]
I think `1. Set the current working directory to the pack directory` is the most multipurpose way to improve the current situation.
